### ISSUE TITLE
Style guide

### ISSUE THREAD

**Issue by jeremiey** [zuri-training/team-15_my-cms#103]

**Comment by Paccid** [comment]
Done
![Screenshot 2022-08-09 085036](https://user-images.githubusercontent.com/105276032/183594928-2d172b09-ceed-4e1a-a2ab-6928961d5ba1.jpg)

**Comment by Emmanuel-Etukudo** [comment]
![image](https://user-images.githubusercontent.com/26837230/183602102-6fe33503-4eeb-4723-b2ed-41e451f33fe5.png)
