### ISSUE TITLE
Dashboard All Users (Hi fi)

### ISSUE THREAD

**Issue by jeremiey** [zuri-training/team-15_my-cms#108]

**Comment by Bisolaawwal** [comment]
![Screenshot_20220809-084206_Chrome](https://user-images.githubusercontent.com/99486416/183593297-faac4868-71bc-43d7-a235-f15efc254b6d.jpg)

**Comment by Bisolaawwal** [comment]
![Screenshot_20220809-084216_Chrome](https://user-images.githubusercontent.com/99486416/183593341-38360f3c-1edb-4d01-80bf-6aada611061c.jpg)

**Comment by Bisolaawwal** [comment]
![Screenshot_20220809-084226_Chrome](https://user-images.githubusercontent.com/99486416/183593405-b3633bde-fc31-4740-ba68-9171a4319eda.jpg)
