### ISSUE TITLE
Verification email sent page

### ISSUE THREAD

**Issue by jeremiey** [zuri-training/team-15_my-cms#122]
<https://www.figma.com/file/Uujc2NV7Sx6qOsWX9JYl0v/Team-15_My-cms?node-id=1086%3A241>

![image](https://user-images.githubusercontent.com/87664239/183857515-37c6755d-311a-488d-8979-326155362653.png)

**Comment by Chelsofia** [comment]
![image](https://user-images.githubusercontent.com/86608086/183971139-8ff85ae4-08cc-493c-af5e-538844a3e025.png)

**Comment by jeremiey** [comment]
Nice work 👍🏽 @Chelsofia
