### ISSUE TITLE
Dashboard: Comments Page

### ISSUE THREAD

**Issue by jeremiey** [zuri-training/team-15_my-cms#124]
<https://www.figma.com/file/Uujc2NV7Sx6qOsWX9JYl0v/Team-15_My-cms?node-id=1108%3A230>

![image](https://user-images.githubusercontent.com/87664239/183858293-c01e77d3-a64a-4d7f-8a02-3a48d307f63c.png)

**Comment by jeremiey** [comment]
Completed ✔️ 

Commits <https://github.com/zuri-training/team-15_my-cms/commit/16abcdf35eb3b744696ec3d898298ae39c3bfa4b> <https://github.com/zuri-training/team-15_my-cms/commit/3a6fe29a8c01a937daff4e34863b9140b570c931>

**Comment by Chelsofia** [comment]
![comments page](https://user-images.githubusercontent.com/86608086/184321274-29ece65d-0a93-4bd4-bb14-ec34370f72e7.jpg)

**Comment by Chelsofia** [comment]
![pacci1](https://user-images.githubusercontent.com/86608086/184321664-95f9fca3-ecdd-4e07-b812-0e98de7f068e.jpg)

**Comment by Chelsofia** [comment]
Done.

**Comment by Chelsofia** [comment]
![image](https://user-images.githubusercontent.com/86608086/184322104-2d4581a3-1003-4862-aca1-6d49384e90ef.png)
