### ISSUE TITLE
Update Login page design

### ISSUE THREAD

**Issue by jeremiey** [zuri-training/team-15_my-cms#143]
### Design to update

![image](https://user-images.githubusercontent.com/87664239/184191000-173a0ec5-56f7-4b8c-a02f-93387ae3b0a9.png)

**Comment by jeremiey** [comment]
### Updated Design

![image](https://user-images.githubusercontent.com/87664239/184191123-cbda6f44-9b82-4704-8b12-6ff00a247a09.png)

**Comment by Paccid** [comment]
This is nicer🤞
