### ISSUE TITLE
Create User Invites and Invite User Page

### ISSUE THREAD

**Issue by jeremiey** [zuri-training/team-15_my-cms#153]
**Invites Page**

https://www.figma.com/file/lKANaLq3ZTbx80EsqDymdn/Team-15_My-cms-(Copy)?node-id=1049%3A1585

![image](https://user-images.githubusercontent.com/87664239/184365917-b88cd77c-8f01-4207-b510-9e24066e8955.png)

**Invite User Page**

https://www.figma.com/file/lKANaLq3ZTbx80EsqDymdn/Team-15_My-cms-(Copy)?node-id=1049%3A1473

![image](https://user-images.githubusercontent.com/87664239/184366069-bbcc7c69-2fb0-40ed-abfd-5c156d7785e1.png)

**Comment by yusufadegbite** [comment]
💯
