### ISSUE TITLE
dashboard/settings page LoFi, HiFi design

### ISSUE THREAD

**Issue by jeremiey** [zuri-training/team-15_my-cms#66]

**Comment by Rhoda-K** [comment]
Done!

**Comment by jeremiey** [comment]
@Rhoda-K 👍🏽

**Comment by Rhoda-K** [comment]
![Screenshot (3)](https://user-images.githubusercontent.com/88286496/183619523-25485101-3cac-4a8a-9dae-15e9925e5808.png)

![Screenshot (4)](https://user-images.githubusercontent.com/88286496/183620410-38da98d4-9a3e-4270-aa27-937f117043bc.png)
