### ISSUE TITLE
dashboard/appearance page design

### ISSUE THREAD

**Issue by jeremiey** [zuri-training/team-15_my-cms#67]

**Comment by Anya-ndulue** [comment]
[](https://www.figma.com/file/qxxVIshxS3sqcpByAS0FzC/Team-15-CMS_-Apperance-page)

**Comment by Anya-ndulue** [comment]
Done

**Comment by Anya-ndulue** [comment]
[https://www.figma.com/file/qxxVIshxS3sqcpByAS0FzC/Team-15-CMS_-Apperance-page]

**Comment by jeremiey** [comment]
Okay. Well done @Anya-ndulue
