### ISSUE TITLE
Sign up | Sign In Page Design

### ISSUE THREAD

**Issue by jeremiey** [zuri-training/team-15_my-cms#71]
![image](https://user-images.githubusercontent.com/87664239/182912340-02ca27a1-45e5-4b99-8f9b-14f0515ffb62.png)

**Comment by Noble101** [comment]
Good job so far bosses

**Comment by jeremiey** [comment]
> Good job so far bosses

Thanks boss

**Comment by yusufadegbite** [comment]
Thanks boss
