### ISSUE TITLE
Description of new user page design

### ISSUE THREAD

**Issue by jeremiey** [zuri-training/team-15_my-cms#74]
![image](https://user-images.githubusercontent.com/87664239/183080171-f55b6ff1-30dd-4544-a6ab-80014883eb9f.png)

**Comment by Noble101** [comment]
Great work!

**Comment by BioMeindinyo** [comment]
![Screenshot (582)](https://user-images.githubusercontent.com/66695096/183309313-2365477f-3187-411a-ac56-251ab1a310ad.png)
Done with this
