### ISSUE TITLE
Choose a URL page design

### ISSUE THREAD

**Issue by jeremiey** [zuri-training/team-15_my-cms#88]
![image](https://user-images.githubusercontent.com/87664239/183382526-c3627ee0-bef9-42e0-a572-61260db1489b.png)

**Comment by Chelsofia** [comment]
Done.

**Comment by Chelsofia** [comment]
![image](https://user-images.githubusercontent.com/86608086/183764087-4faa04d7-6ee7-4bf2-939e-a8c402c76e74.png)

**Comment by Chelsofia** [comment]
![Uploading image.png…]()

**Comment by Chelsofia** [comment]
![image](https://user-images.githubusercontent.com/86608086/183765320-9c3a64d9-47af-4f4e-b845-676370620ed3.png)

**Comment by Chelsofia** [comment]
![image](https://user-images.githubusercontent.com/86608086/183765798-ae63049b-b9d4-4dc1-a302-d2ba73aac0ed.png)

**Comment by jeremiey** [comment]
Nice work.
