### ISSUE TITLE
Marketing and integrations page design

### ISSUE THREAD

**Issue by jeremiey** [zuri-training/team-15_my-cms#89]
```dashboard/tools```

![image](https://user-images.githubusercontent.com/87664239/183391231-8fbac1f3-c66a-4863-9e4a-509d52f14d79.png)

**Comment by Noble101** [comment]
Done

**Comment by Noble101** [comment]
![Marketing and Integrations](https://user-images.githubusercontent.com/105364216/183843697-b1757f23-2a68-47f6-9444-2c6ad1e6bb97.png)

**Comment by jeremiey** [comment]
Job well done @Noble101

**Comment by Noble101** [comment]
Thank You!
