### ISSUE TITLE
Update sign-up page, login page design

### ISSUE THREAD

**Issue by jeremiey** [zuri-training/team-15_my-cms#90]
## Screenshots of pages to be updated

![image](https://user-images.githubusercontent.com/87664239/183392274-df6361a6-bc87-4d61-bf14-755ec0867029.png)

![image](https://user-images.githubusercontent.com/87664239/183392623-b7cbee02-e1aa-4e92-ba2f-d53c28c53109.png)

**Comment by Musoye** [comment]
Working on it.

**Comment by Musoye** [comment]
Done
