### ISSUE TITLE
Select template page

### ISSUE THREAD

**Issue by jeremiey** [zuri-training/team-15_my-cms#94]
![image](https://user-images.githubusercontent.com/87664239/183403594-a1a5c839-ff6a-4ace-bf87-319ca7d71d84.png)

**Comment by steph-ayo** [comment]
Successfully completed the task

**Comment by steph-ayo** [comment]
Successfully completed the task

**Comment by jeremiey** [comment]
Nicely done 👍🏽  @steph-ayo
