### ISSUE TITLE
Update confirm sign-out page design

### ISSUE THREAD

**Issue by jeremiey** [zuri-training/team-15_my-cms#96]
**Current**
![image](https://user-images.githubusercontent.com/87664239/183392688-017c3f7f-2e85-4fc6-92ef-f766713ae35b.png)

**Target**
![image](https://user-images.githubusercontent.com/87664239/183420959-51acb351-4436-487d-a5cd-6012cabee310.png)

**Comment by Musoye** [comment]
OK I'm working on it.

**Comment by Musoye** [comment]
I have finish  working on it. 
![Screenshot (213)](https://user-images.githubusercontent.com/103517645/183569476-0e62390f-4306-4abe-b150-f2e7374beba8.png)
